# -*- coding: utf-8 -*-
"""Assets_OCI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Em-TaBgG8m4HB8p1C5Fzsqri3DB2__2
"""

!pip install oracledb yfinance pandas-ta "pandas<3.0.0" --quiet

from google.colab import files
import os

# 1. Upload the zip
print("Please upload your OCI Wallet zip file:")
uploaded = files.upload()
wallet_zip = list(uploaded.keys())[0]

# 2. Unzip to a clean folder
!mkdir -p /content/wallet
!unzip -o {wallet_zip} -d /content/wallet

# 3. Verify - this should show 'tnsnames.ora'
print("\nWallet files prepared:")
!ls /content/wallet

# --- 1. CLEAN DATA FETCHING (2-Decimal Precision Fix) ---
import yfinance as yf
import pandas_ta as ta
import pandas as pd
import oracledb

# The assets you chose: Gold, Silver, and Copper (Bronze)
assets = ["GC=F", "SI=F", "HG=F"]
all_rows = []

print("Consulting market assets and applying 2-decimal rounding...")

for symbol in assets:
    # Fetch 2 months of data
    df = yf.download(symbol, period="2mo", interval="1d", progress=False)

    # Fix for yfinance MultiIndex (The "AttributeError" fix)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    # Calculate RSI
    df.ta.rsi(length=14, append=True)

    # Remove rows with empty values (The "DPY-4004" fix)
    df = df.dropna(subset=['High', 'Low', 'RSI_14'])

    for index, row in df.iterrows():
        # APPLYING ROUND(x, 2) TO EVERYTHING
        all_rows.append((
            symbol,
            index.to_pydatetime(),
            round(float(row['Open']), 2),
            round(float(row['High']), 2),
            round(float(row['Low']), 2),
            round(float(row['Close']), 2),
            round(float(row['RSI_14']), 2)
        ))

print(f"Extraction Complete! {len(all_rows)} clean rows ready for OCI.")

# Quick Preview of the rounded data
preview_df = pd.DataFrame(all_rows, columns=['Asset', 'Date', 'Open', 'High', 'Low', 'Close', 'RSI'])
print("\nPreview of Clean Data:")
print(preview_df.tail(5))

import oracledb
import getpass

# --- CREDENTIAL CHECK ---
# This ensures the script asks for your passwords if they are not in memory
user = "ADMIN"

if 'db_password' not in locals():
    db_password = getpass.getpass("Enter OCI Database (ADMIN) Password: ")

if 'wallet_password' not in locals():
    wallet_password = getpass.getpass("Enter Wallet (.zip) Password: ")

# --- 2. THE FINAL SYNC (MERGE) WITH ROUNDED DATA ---
try:
    print("Opening OCI Connection...")
    # Note: wallet_password is now a variable, not a "text string"
    conn = oracledb.connect(
        user=user,
        password=db_password,
        dsn="marketdb_high",
        config_dir="/content/wallet",
        wallet_location="/content/wallet",
        wallet_password=wallet_password
    )

    with conn.cursor() as cursor:
        # Prevent ORA-12838: Disabling parallel DML for this session
        cursor.execute("ALTER SESSION DISABLE PARALLEL DML")

        # The SQL Logic: 7 columns, 7 placeholders (:1 to :7)
        sql = """
        MERGE INTO market_assets t
        USING (SELECT :1 as s, :2 as d, :3 as o, :4 as h, :5 as l, :6 as c, :7 as r FROM dual) src
        ON (t.asset_symbol = src.s AND t.trade_date = src.d)
        WHEN NOT MATCHED THEN
            INSERT (asset_symbol, trade_date, open_price, high_price, low_price, close_price, rsi_14)
            VALUES (src.s, src.d, src.o, src.h, src.l, src.c, src.r)
        WHEN MATCHED THEN
            UPDATE SET
                open_price = src.o,
                high_price = src.h,
                low_price = src.l,
                close_price = src.c,
                rsi_14 = src.r
        """

        # Execute the merge using the rounded data from Step 1
        cursor.executemany(sql, all_rows)
        conn.commit()
        print(f"SUCCESS! {len(all_rows)} rows updated with 2-decimal precision in OCI.")

except Exception as e:
    print(f"Connection Failed: {e}")

finally:
    # Safely close the connection to free up OCI resources
    if 'conn' in locals() and conn:
        conn.close()
        print("OCI Connection closed safely.")

# --- STEP 3: FINAL VERIFICATION ---
print("\nLatest 5 records in your OCI Database:")
# (This part is optional but helps you see the High/Low columns are filled)
print(pd.DataFrame(all_rows, columns=['Asset', 'Date', 'Open', 'High', 'Low', 'Close', 'RSI']).tail(5))

import matplotlib.pyplot as plt

# --- 1. Map Symbols to Names for the Graph ---
name_map = {
    'GC=F': 'Gold (Ouro)',
    'SI=F': 'Silver (Prata)',
    'HG=F': 'Copper (Cobre)'
}

# --- 2. Filter data for the last 10 days ---
# We use the preview_df created in your script
preview_df['Date'] = pd.to_datetime(preview_df['Date'])
last_10_days = preview_df.sort_values('Date').groupby('Asset').tail(10).copy()

# Add the friendly name column
last_10_days['Name'] = last_10_days['Asset'].map(name_map)

# --- 3. Create the Visualization ---
plt.figure(figsize=(12, 6))

for asset_name in last_10_days['Name'].unique():
    subset = last_10_days[last_10_days['Name'] == asset_name]
    plt.plot(subset['Date'], subset['Close'], marker='o', label=asset_name)

    # Add price labels to each point
    for x, y in zip(subset['Date'], subset['Close']):
        plt.text(x, y, f'${y:.2f}', fontsize=9, verticalalignment='bottom')

plt.title('Market Assets - Last 10 Days (Closing Price)', fontsize=14)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Price (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()

plt.show()

